services:
  video_server:
    image: "bluenviron/mediamtx"
    network_mode: "host"
  video_stream:
    image: "jrottenberg/ffmpeg"
    network_mode: "host"
    volumes:
      - type: bind
        source: "video.mov"
        target: "/video.mov"
    command: "-re -stream_loop -1 -i /video.mov -c:v libx264 -c:a copy -f rtsp rtsp://localhost:8554/vsa"
